<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

<body>
    <h1> Suas Informações </h1>
    <?php
    echo $response ? '<p>Seus dados foram armazenado corretamente.</p>' :  'falha ao armazenar os dados';
    ?>
    <p>Nome: <?= $user['nome'] ?> </p>
    <p>Email: <?= $user['email'] ?> </p>
    <p>Senha: <?= $user['senha'] ?> </p>
    <p>Telefone: <?= $user['telefone'] ?> </p>
</body>

</html>