<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <title></title>
</head>

<body>
  <a href="/user/logout"> Sair </a>
  <div align=center>
    <h1>Usuários</h1>
  </div>
  <?php foreach ($users as $user) { ?>
    <p>Nome: <?= $user['nome']; ?> </p>
    <p>Email: <?= $user['email']; ?> </p>
    <p>Senha: <?= $user['senha']; ?> </p>
    <p>mensagem: <?= $user['mensagem']; ?> </p>

    <a href="/user/delete/<?= $user['id']; ?> " class="btn btn-danger">Deletar </a>
    <a href="/user/edit/<?= $user['id']; ?> " class="btn btn-primary">Editar </a>

    <hr>
  <?php } ?>
</body>

</html>