<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <div align=center>
    <h1>Usuários</h1>
  </div>
  <?php foreach ($users as $user) { ?>
    <p>Nome: <?= $user['nome']; ?> </p>
    <p>Email: <?= $user['email']; ?> </p>
    <p>Senha: <?= $user['senha']; ?> </p>
    <p>Telefone: <?= $user['telefone']; ?> </p>
    <hr>
  <?php } ?>
</body>

</html>